name = "BMSOS"
uuid = "288039e9-afd1-4944-b7ae-3ac2e056f6e9"
authors = ["Benoît Legat <benoit.legat@gmail.com> and Chenyang Yuan <yuanchenyang@gmail.com>"]
version = "0.0.1-DEV"

[deps]
AutoGrad = "6710c13c-97f1-543f-91c5-74e8f7d95b35"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
TrigPolys = "bbdedc48-cb31-4a37-9fe3-b015aecc8dd3"

[compat]
AutoGrad = "1"
NLopt = "0.6"
TrigPolys = "0.1"
julia = "1.6"
